services:
  db:
    image: postgres:17.2
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
  web:
    build: .
    command: uv run fastapi dev app/main.py --port 80 --host 0.0.0.0
    develop:
      watch:
        - action: rebuild
          path: pyproject.toml
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
